name: Build and Increment Version

on:
  push:
    branches:
      - GuyEdri-patch-1  # Adjust the branch name as needed

jobs:
  build-and-increment:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set Version and Build JAR
        run: |
          MAJOR=1  # Update with your desired major version
          MINOR=0  # Update with your desired minor version
          PATCH=$(date +'%Y%m%d%H%M%S')  # Generate a patch based on current date and time
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=${NEW_VERSION}
          mvn clean package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: target/my-app*

