name: Build, Version, and Deploy

on:
  push:
    branches:
      - GuyEdri-patch-1

jobs:
  build-version-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set Version and Build JAR
        run: |
          MAJOR=1
          MINOR=0
          PATCH=$(date +'%Y%m%d%H%M%S')
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          mvn versions:set -DnewVersion=${NEW_VERSION}
          mvn clean package

      - name: Deploy to GitHub Package Registry
        run: |
          mvn deploy -Dmaven.repo.local=$HOME/.m2/repository \
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/GuyEdri/simple-java-maven-app \
            -Duser.name=GuyEdri -Duser.email=github@users.noreply.github.com \
            -Dgpg.executable=gpg -Dgpg.passphrase=${{ secrets.githubpackage }}

