name: Java CI with Maven and Deployment

on:
  push:
    branches: [ "GuyEdri-patch-1" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Set Version using Run Number
      run: echo "NEW_VERSION=1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Update Version in POM
      run: mvn versions:set -DnewVersion=$NEW_VERSION

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Docker steps (same as before)

    # Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.LOCAL_MACHINE_SSH_KEY }}

    # Deployment using SSH
    - name: Deploy to Local Machine
      run: ssh ubuntu@54.153.64.55 "docker run guyedri/java:1.0.10"

